# Generated by Django 5.2.4 on 2025-08-03 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_donation_payment_status_donation_stripe_charge_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='stripe_charge_id',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='stripe_payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
